/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class extmem_Memory */

#ifndef _Included_extmem_Memory
#define _Included_extmem_Memory
#ifdef __cplusplus
extern "C" {
#endif
    /*
    * Class:     extmem_Memory
    * Method:    openProcess
    * Signature: (Ljava/lang/String;)J
    */
    JNIEXPORT jlong JNICALL Java_extmem_Memory_openProcess
    (JNIEnv *, jclass, jstring);

    /*
    * Class:     extmem_Memory
    * Method:    closeProcess
    * Signature: (J)V
    */
    JNIEXPORT void JNICALL Java_extmem_Memory_closeProcess
    (JNIEnv *, jclass, jlong);

    /*
    * Class:     extmem_Memory
    * Method:    readBytes
    * Signature: (JJI)[B
    */
    JNIEXPORT jbyteArray JNICALL Java_extmem_Memory_readBytes
    (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
